### ISSUE TITLE
1.2.35: build fails

### ISSUE THREAD

**Issue by kloczek** [lsh123/xmlsec#411] opened 2022-10-24 22:38 UTC
autoconf output:
<details>

```console
+ ./configure --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --bindir=/usr/bin --datadir=/usr/share --disable-dependency-tracking --exec-prefix=/usr --includedir=/usr/include --infodir=/usr/share/info --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --mandir=/usr/share/man --prefix=/usr --program-prefix= --runstatedir=/run --sbindir=/usr/sbin --sharedstatedir=/var/lib --sysconfdir=/etc --disable-static --enable-pkgconfig
checking build system type... x86_64-redhat-linux-gnu
checking host system type... x86_64-redhat-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '1000' is supported by ustar format... yes
checking whether GID '1000' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking whether to enable maintainer-specific portions of Makefiles... no
checking whether make supports nested variables... (cached) yes
checking for x86_64-redhat-linux-gnu-gcc... /usr/bin/gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether /usr/bin/gcc accepts -g... yes
checking for /usr/bin/gcc option to enable C11 features... none needed
checking whether /usr/bin/gcc understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of /usr/bin/gcc... none
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by /usr/bin/gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/gcc-nm
checking the name lister (/usr/bin/gcc-nm) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-redhat-linux-gnu file names to x86_64-redhat-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-redhat-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for x86_64-redhat-linux-gnu-file... no
checking for file... file
checking for x86_64-redhat-linux-gnu-objdump... no
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for x86_64-redhat-linux-gnu-dlltool... no
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for x86_64-redhat-linux-gnu-ar... /usr/bin/gcc-ar
checking for archiver @FILE support... @
checking for x86_64-redhat-linux-gnu-strip... no
checking for strip... strip
checking for x86_64-redhat-linux-gnu-ranlib... /usr/bin/gcc-ranlib
checking command to parse /usr/bin/gcc-nm output from /usr/bin/gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for x86_64-redhat-linux-gnu-mt... no
checking for mt... no
checking if : is a manifest tool... no
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if /usr/bin/gcc supports -fno-rtti -fno-exceptions... no
checking for /usr/bin/gcc option to produce PIC... -fPIC -DPIC
checking if /usr/bin/gcc PIC flag -fPIC -DPIC works... yes
checking if /usr/bin/gcc static flag -static works... no
checking if /usr/bin/gcc supports -c -o file.o... yes
checking if /usr/bin/gcc supports -c -o file.o... (cached) yes
checking whether the /usr/bin/gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking for egrep... (cached) /usr/bin/grep -E
checking for cp... /usr/bin/cp
checking for mv... /usr/bin/mv
checking for tar... /usr/bin/tar
checking for perl... /usr/bin/perl
checking for help2man... no
checking for xsltproc... /usr/bin/xsltproc
checking for man2html... no
checking for gtkdoc-mkhtml... no
checking for gtkdoc-mkdb... no
checking for gtkdoc-scan... no
checking for dirent.h that defines DIR... yes
checking for library containing opendir... none required
checking for build OS... "Linux"
checking for development environment... disabled
checking for man pages build... disabled
checking for docs build... disabled
checking for shared library suffix... .so
checking for __FUNCTION__ or __func__... __func__
checking for x86_64-redhat-linux-gnu-pkg-config... no
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking size of size_t... 8
checking for using size_t... no
checking for libxml-2.0 >= 2.8.0... yes
checking for libxml2 library >= 2.8.0... checking how to run the C preprocessor... /usr/bin/gcc -E
yes
checking for libxslt >= 1.0.20... yes
checking for libxslt library >= 1.0.20... yes
checking for openssl >= 1.0.0... yes
checking for openssl library >= 1.0.0... yes (openssl version '3.0.5')
checking for seamonkey-nspr >= 4.25.1... no
checking for mozilla-nspr >= 1.4... no
checking for xulrunner-nspr >= 4.25.1... no
checking for nspr >= 4.25.1... yes
checking for seamonkey-nss >= 1.0... no
checking for mozilla-nss >= 1.4... no
checking for xulrunner-nss >= 3.50.1... no
checking for nss >= 3.50.1... yes
checking for nspr library >= 4.25.1... yes
checking for nss library >= 3.50.1... yes
checking for gcrypt >= 1.4.0... no
checking for libgcrypt20 >= 1.4.0... no
checking for libgcrypt11 >= 1.4.0... no
checking for libgcrypt >= 1.4.0... yes
checking for libgcrypt library >= 1.4.0... yes
checking for gnutls >= 2.8.0... yes
checking for libgnutls library >= 2.8.0... yes
checking for mscrypto... disabled
checking for mscng... disabled
checking for default crypto library... yes ("openssl")
checking for MD5 support... yes
checking for RIPEMD-160 support... yes
checking for SHA1 support... yes
checking for SHA224 support... yes
checking for SHA256 support... yes
checking for SHA384 support... yes
checking for SHA512 support... yes
checking for HMAC support... yes
checking for DSA support... yes
checking for RSA support... yes
checking for x509 support... yes
checking for DES support... yes
checking for AES support... yes
checking for GOST support... disabled
checking for EXPERMIENTAL GOST2012 support... disabled
checking for XMLDSig support... yes
checking for XMLEnc support... yes
checking for soap support... disabled
checking for mans... yes
checking for docs... yes
checking for apps... yes
checking for static linking... disabled
checking for ltdl.h... yes
checking for lt_dlopenext in -lltdl... yes
checking for xmlsec-crypto dynamic loading support... yes
checking for xmlsec-crypto dynamic loading support in command line tool... yes
checking for docs folder... $(htmldir)
checking for Simple Keys Manager testing... yes
checking for templates testing... yes
checking for debugging... disabled
checking for warnings as errors... disabled
checking for profiling... disabled
checking for pedantic... disabled
checking for secure memset... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating include/xmlsec/openssl/Makefile
config.status: creating src/openssl/Makefile
config.status: creating include/xmlsec/gnutls/Makefile
config.status: creating src/gnutls/Makefile
config.status: creating include/xmlsec/gcrypt/Makefile
config.status: creating src/gcrypt/Makefile
config.status: creating include/xmlsec/nss/Makefile
config.status: creating src/nss/Makefile
config.status: creating xmlsec1.pc
config.status: creating include/xmlsec/version.h
config.status: creating Makefile
config.status: creating include/Makefile
config.status: creating include/xmlsec/Makefile
config.status: creating src/Makefile
config.status: creating apps/Makefile
config.status: creating docs/Makefile
config.status: creating docs/api/Makefile
config.status: creating man/Makefile
config.status: creating xmlsec1-openssl.pc
config.status: creating xmlsec1-gnutls.pc
config.status: creating xmlsec1-gcrypt.pc
config.status: creating xmlsec1-nss.pc
config.status: creating xmlsec1.spec
config.status: creating xmlsec1Conf.sh
config.status: creating xmlsec1-config
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands
```
</details>

And build fails with
<details>

```console
[tkloczko@devel-g2v xmlsec1-1.2.35]$ make
make  all-recursive
make[1]: Entering directory '/home/tkloczko/rpmbuild/BUILD/xmlsec1-1.2.35'
Making all in include
make[2]: Entering directory '/home/tkloczko/rpmbuild/BUILD/xmlsec1-1.2.35/include'
Making all in xmlsec
make[3]: Entering directory '/home/tkloczko/rpmbuild/BUILD/xmlsec1-1.2.35/include/xmlsec'
Making all in openssl
make[4]: Entering directory '/home/tkloczko/rpmbuild/BUILD/xmlsec1-1.2.35/include/xmlsec/openssl'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/xmlsec1-1.2.35/include/xmlsec/openssl'
Making all in nss
make[4]: Entering directory '/home/tkloczko/rpmbuild/BUILD/xmlsec1-1.2.35/include/xmlsec/nss'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/xmlsec1-1.2.35/include/xmlsec/nss'
Making all in gcrypt
make[4]: Entering directory '/home/tkloczko/rpmbuild/BUILD/xmlsec1-1.2.35/include/xmlsec/gcrypt'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/xmlsec1-1.2.35/include/xmlsec/gcrypt'
Making all in gnutls
make[4]: Entering directory '/home/tkloczko/rpmbuild/BUILD/xmlsec1-1.2.35/include/xmlsec/gnutls'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/xmlsec1-1.2.35/include/xmlsec/gnutls'
make[4]: Entering directory '/home/tkloczko/rpmbuild/BUILD/xmlsec1-1.2.35/include/xmlsec'
make[4]: Nothing to be done for 'all-am'.
make[4]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/xmlsec1-1.2.35/include/xmlsec'
make[3]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/xmlsec1-1.2.35/include/xmlsec'
make[3]: Entering directory '/home/tkloczko/rpmbuild/BUILD/xmlsec1-1.2.35/include'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/xmlsec1-1.2.35/include'
make[2]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/xmlsec1-1.2.35/include'
Making all in src
make[2]: Entering directory '/home/tkloczko/rpmbuild/BUILD/xmlsec1-1.2.35/src'
Making all in .
make[3]: Entering directory '/home/tkloczko/rpmbuild/BUILD/xmlsec1-1.2.35/src'
  CC       base64.lo
In file included from base64.c:31:
cast_helpers.h:24:28: error: missing binary operator before token "0"
   24 | #define SIZE_MAX (~(size_t)0)
      |                            ^
cast_helpers.h:110:6: note: in expansion of macro 'SIZE_MAX'
  110 | #if (SIZE_MAX > INT_MAX)
      |      ^~~~~~~~
cast_helpers.h:24:28: error: missing binary operator before token "0"
   24 | #define SIZE_MAX (~(size_t)0)
      |                            ^
cast_helpers.h:164:6: note: in expansion of macro 'SIZE_MAX'
  164 | #if (SIZE_MAX > UINT_MAX)
      |      ^~~~~~~~
cast_helpers.h:24:28: error: missing binary operator before token "0"
   24 | #define SIZE_MAX (~(size_t)0)
      |                            ^
cast_helpers.h:200:6: note: in expansion of macro 'SIZE_MAX'
  200 | #if (SIZE_MAX > LONG_MAX)
      |      ^~~~~~~~
cast_helpers.h:24:28: error: missing binary operator before token "0"
   24 | #define SIZE_MAX (~(size_t)0)
      |                            ^
cast_helpers.h:340:6: note: in expansion of macro 'SIZE_MAX'
  340 | #if (SIZE_MAX > XMLSEC_SIZE_MAX)
      |      ^~~~~~~~
make[3]: *** [Makefile:700: base64.lo] Error 1
make[3]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/xmlsec1-1.2.35/src'
```
</details>

**Comment by lsh123** [comment] 2022-10-24 22:50
Thanks! Interestingly, my builds all work just fine on Ubuntu:

https://github.com/lsh123/xmlsec/actions/runs/3316325795

This is likely caused by gcc pre-processor that doesn't like the cast in #define. Can you check if you have SIZE_MAX defined in /usr/include files and if yes -- which one?

**Comment by lsh123** [comment] 2022-10-24 22:51
It should be in stdint.h

**Comment by lsh123** [comment] 2022-10-24 22:57
Any chance you can also try this PR to see if it fixes the issue?

https://github.com/lsh123/xmlsec/pull/412

**Comment by kloczek** [comment] 2022-10-25 00:34
from /usr/include/stdint.h:
```c
/* Limit of `size_t' type.  */
# if __WORDSIZE == 64
#  define SIZE_MAX              (18446744073709551615UL)
# else
#  if __WORDSIZE32_SIZE_ULONG
#   define SIZE_MAX             (4294967295UL)
#  else
#   define SIZE_MAX             (4294967295U)
#  endif
# endif
```

**Comment by lsh123** [comment] 2022-10-25 00:36
Perfect, the PR above should fix it for you I believe.

**Comment by kloczek** [comment] 2022-10-25 00:36
> Any chance you can also try this PR to see if it fixes the issue?
> 
> #412

Just tested that PR and it does not apply cleanly on top of last sdk release
```console
warning: Downloading https://github.com/KhronosGroup/Vulkan-ValidationLayers//archive/sdk-1.3.231/vulkan-validation-layers-1.3.231.tar.gz to /home/tkloczko/rpmbuild/SOURCES/vulkan-validation-layers-1.3.231.tar.gz
warning: Downloading https://github.com/KhronosGroup/Vulkan-ValidationLayers//pull/412.patch#/vulkan-validation-layers-fix-size_max.patch to /home/tkloczko/rpmbuild/SOURCES/vulkan-validation-layers-fix-size_max.patch
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.8fEtHT
+ umask 022
+ cd /home/tkloczko/rpmbuild/BUILD
+ cd /home/tkloczko/rpmbuild/BUILD
+ rm -rf Vulkan-ValidationLayers-sdk-1.3.231
+ /usr/bin/gzip -dc /home/tkloczko/rpmbuild/SOURCES/vulkan-validation-layers-1.3.231.tar.gz
+ /usr/bin/tar -xof -
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd Vulkan-ValidationLayers-sdk-1.3.231
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ /usr/bin/cat /home/tkloczko/rpmbuild/SOURCES/vulkan-validation-layers-fix_shared.patch
+ /usr/bin/patch -p1 -s --fuzz=0 --no-backup-if-mismatch -f
+ /usr/bin/cat /home/tkloczko/rpmbuild/SOURCES/vulkan-validation-layers-fix-size_max.patch
+ /usr/bin/patch -p1 -s --fuzz=0 --no-backup-if-mismatch -f
9 out of 9 hunks FAILED -- saving rejects to file scripts/object_tracker_generator.py.rej
6 out of 6 hunks FAILED -- saving rejects to file scripts/object_tracker_generator.py.rej
The text leading up to this was:
--------------------------
|
|From 19332e58aa3c21985419453a009a12b5b9e02a70 Mon Sep 17 00:00:00 2001
|From: Mark Lobodzinski <mark@lunarg.com>
|Date: Wed, 12 Sep 2018 18:09:49 -0600
|Subject: [PATCH 03/17] layers: Split OT validate/record steps
|
|The DestroyObject function performed validation and state recording.
|Split these functions out into separate functions.
|
|Change-Id: I3d38a197983ccd3ad17321c3e9ed35fb34679cbd
|---
| layers/object_tracker.h             | 51 ++++++++++++++---------
| layers/object_tracker_utils.cpp     | 63 ++++++++++++++++++-----------
| scripts/object_tracker_generator.py |  3 +-
| 3 files changed, 72 insertions(+), 45 deletions(-)
|
|diff --git a/layers/object_tracker.h b/layers/object_tracker.h
|index 7d7880edf4d..e2f4cc56177 100644
|--- a/layers/object_tracker.h
|+++ b/layers/object_tracker.h
--------------------------
No file to patch.  Skipping patch.
2 out of 2 hunks ignored
12 out of 12 hunks FAILED -- saving rejects to file layers/object_tracker_utils.cpp.rej
1 out of 1 hunk FAILED -- saving rejects to file scripts/object_tracker_generator.py.rej
The text leading up to this was:
--------------------------
|
|From 74b97e3066f3175a845a4c91eb82d8ce74e1d48e Mon Sep 17 00:00:00 2001
|From: Mark Lobodzinski <mark@lunarg.com>
|Date: Thu, 13 Sep 2018 14:44:28 -0600
|Subject: [PATCH 04/17] layers: Plumb OT failure codes through to user
|
|The return values of many OT log_msg() calls were ignored. Enabled
|user-control of down-chain calls for these errors.
|
|Change-Id: I3b440b270d429f55608ca506d3b6e1911e9c50ee
|---
| layers/object_tracker.h             |  4 ++--
| layers/object_tracker_utils.cpp     | 11 +++++++----
| scripts/object_tracker_generator.py |  8 +++++---
| 3 files changed, 14 insertions(+), 9 deletions(-)
|
|diff --git a/layers/object_tracker.h b/layers/object_tracker.h
|index e2f4cc56177..4f4f570007c 100644
|--- a/layers/object_tracker.h
|+++ b/layers/object_tracker.h
--------------------------
No file to patch.  Skipping patch.
2 out of 2 hunks ignored
1 out of 1 hunk FAILED -- saving rejects to file layers/object_tracker_utils.cpp.rej
1 out of 1 hunk FAILED -- saving rejects to file scripts/object_tracker_generator.py.rej
8 out of 8 hunks FAILED -- saving rejects to file scripts/object_tracker_generator.py.rej
5 out of 5 hunks FAILED -- saving rejects to file layers/object_tracker_utils.cpp.rej
2 out of 2 hunks FAILED -- saving rejects to file layers/object_tracker_utils.cpp.rej
3 out of 3 hunks FAILED -- saving rejects to file layers/object_tracker_utils.cpp.rej
3 out of 3 hunks FAILED -- saving rejects to file layers/object_tracker_utils.cpp.rej
6 out of 6 hunks FAILED -- saving rejects to file layers/object_tracker_utils.cpp.rej
10 out of 10 hunks FAILED -- saving rejects to file layers/object_tracker_utils.cpp.rej
The text leading up to this was:
--------------------------
|
|From b070dbfc07a8599c30eeff3ddee85dd0c2926c1d Mon Sep 17 00:00:00 2001
|From: Mark Lobodzinski <mark@lunarg.com>
|Date: Thu, 20 Sep 2018 11:05:57 -0600
|Subject: [PATCH 12/17] layers: Split OT inst/dev layer data maps
|
|Including making instance/device versions of object tracking and
|validation routines. This is necessary to be consistent with other
|layer models.
|
|Change-Id: I13a5942cbef06ca392b32e140bde727d52992946
|---
| layers/object_tracker.h             | 271 +++++++++------
| layers/object_tracker_utils.cpp     | 496 ++++++++++++++--------------
| scripts/object_tracker_generator.py |  27 +-
| 3 files changed, 449 insertions(+), 345 deletions(-)
|
|diff --git a/layers/object_tracker.h b/layers/object_tracker.h
|index 4f4f570007c..2c288527c7f 100644
|--- a/layers/object_tracker.h
|+++ b/layers/object_tracker.h
--------------------------
No file to patch.  Skipping patch.
5 out of 5 hunks ignored
89 out of 89 hunks FAILED -- saving rejects to file layers/object_tracker_utils.cpp.rej
4 out of 4 hunks FAILED -- saving rejects to file scripts/object_tracker_generator.py.rej
1 out of 1 hunk FAILED -- saving rejects to file layers/CMakeLists.txt.rej
1 out of 1 hunk FAILED -- saving rejects to file layers/object_lifetime_validation.h.rej
The text leading up to this was:
--------------------------
|diff --git a/layers/object_tracker.h b/layers/object_tracker.h
|index 2c288527c7f..74ec2b30eb8 100644
|--- a/layers/object_tracker.h
|+++ b/layers/object_tracker.h
--------------------------
No file to patch.  Skipping patch.
3 out of 3 hunks ignored
41 out of 41 hunks FAILED -- saving rejects to file layers/object_tracker_utils.cpp.rej
1 out of 1 hunk FAILED -- saving rejects to file scripts/lvl_genvk.py.rej
9 out of 9 hunks FAILED -- saving rejects to file scripts/object_tracker_generator.py.rej
2 out of 2 hunks FAILED -- saving rejects to file scripts/lvl_genvk.py.rej
2 out of 2 hunks FAILED -- saving rejects to file layers/CMakeLists.txt.rej
2 out of 2 hunks FAILED -- saving rejects to file layers/CMakeLists.txt.rej
2 out of 2 hunks FAILED -- saving rejects to file layers/object_lifetime_validation.h.rej
1 out of 1 hunk FAILED -- saving rejects to file layers/object_tracker.h.rej
40 out of 40 hunks FAILED -- saving rejects to file layers/object_tracker_utils.cpp.rej
2 out of 2 hunks FAILED -- saving rejects to file scripts/lvl_genvk.py.rej
13 out of 13 hunks FAILED -- saving rejects to file scripts/object_tracker_generator.py.rej
1 out of 1 hunk FAILED -- saving rejects to file tests/CMakeLists.txt.rej
```

**Comment by lsh123** [comment] 2022-10-25 00:37
hm... these aren't xmlsec files

**Comment by kloczek** [comment] 2022-10-25 00:39
Sorry .. wrong ticket 😄 
I'll delete that

**Comment by kloczek** [comment] 2022-10-25 00:40
Ah .. I've applied that on top of wrong spec file 😋

**Comment by kloczek** [comment] 2022-10-25 00:44
OK with that PR I was able to build 1.2.35.

**Comment by lsh123** [comment] 2022-10-25 00:48
Great, I will have a new release early next week to update docs for retiring xmlsec mailing list (https://www.aleksey.com/pipermail/xmlsec/2022/010496.html), this PR will be included.

**Closed** 2022-10-25 00:48 UTC

**Comment by kloczek** [comment] 2022-10-25 00:52
Thank you 👍  and sorry for the messy reply 😋
